[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "brukeropus"
<<<<<<< HEAD
version = "1.0.3"
=======
version = "1.0.4"
>>>>>>> origin/master
authors = [
  { name="Josh Duran", email="josh.m.duran@gmail.com" },
]
description = "A python package for communicating with Bruker OPUS spectroscopy software and reading its binary file format."
readme = "README.md"
dependencies = ["numpy"]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://github.com/joshduran/brukeropus"
Issues = "https://github.com/joshduran/brukeropus/issues"
Documentation = "https://joshduran.github.io/brukeropus/brukeropus.html"