# This workflow runs tests for BrukerOpus across different operating systems and Python versions
# It ensures the package works correctly in various environments

name: Tests

# Define when this workflow should run:
# - On push to main and tests branches
# - Weekly on Sunday at midnight to ensure that package update are not problematic
# - On pull requests
# - Manually from GitHub interface
on:
  push:
    branches:
      - master
      - tests/*
      
  schedule:
    - cron: "0 0 * * 0"  # At 00:00 on Sunday

  pull_request:

  workflow_dispatch:  # Manual trigger

# Prevent multiple simultaneous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-package:

    name: Test using ${{ matrix.os }} and python ${{ matrix.pythonVersion }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash {0}
        # do not use -l flag (do not work with macos when bash is se in login mode)

    # Define test matrix - this will run tests in parallel for:
    # - Different operating systems (Ubuntu, macOS, Windows)
    # - Different Python versions (3.10, 3.13)
    strategy:
      fail-fast: false  # Continue testing even if one combination fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pythonVersion: ["3.10", "3.13"]

    steps:
      # Print debug information about the current run
      - name: info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "pythonVersion: ${{ matrix.pythonVersion }}"
          echo "os: ${{ matrix.os }}"

      - name: Checkout brukeropus repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.pythonVersion }}
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Install brukeropus
        run: |
          python -m pip install pytest coverage
          python -m pip install .
          
      - name: Test with coverage
        run: |
          coverage run -m pytest tests

      - name: Coverage report to html
        run: |
          coverage html

      - name: Upload coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.pythonVersion == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            htmlcov/index.html
          retention-days: 5